name: WORKFLOW -- CI Deploy Pipeline
on:
  pull_request:
    types: [opened, edited]
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  test_job:
    name: JOB -- Test Job
    runs-on: ubuntu-latest
    steps:
      - name: STEP -- Checkout repository
        uses: actions/checkout@v5

      - name: STEP -- Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24.11.0'

      - name: STEP -- Install dependencies
        run: |
            npm install -g yarn
            yarn --cwd frontend/apps/starting-app install

      - name: STEP -- Run tests
        run: |
            yarn --cwd frontend/apps/starting-app test
  
  build-job:
    name: JOB -- Build Job
    runs-on: ubuntu-latest
    steps:
      - name: STEP -- Checkout repository
        uses: actions/checkout@v5

      - name: STEP -- Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24.11.0'

      - name: STEP -- Install dependencies
        run: |
            npm install -g yarn
            yarn --cwd frontend/apps/starting-app install

      - name: STEP -- Build application
        run: |
            yarn --cwd frontend/apps/starting-app build

  deploy-job:
      name: JOB -- Deploy Job
      runs-on: ubuntu-latest
      needs: [build-job, test_job]
      steps:
        - name: STEP -- Checkout repository
          uses: actions/checkout@v5
        - name: STEP -- Set up Node.js
          uses: actions/setup-node@v6
          with:
            node-version: '24.11.0'

        - name: STEP -- Install dependencies
          run: |
            npm install -g yarn
            yarn --cwd frontend/apps/starting-app install

        - name: STEP -- Deploy application
          run: |
            echo "Deploying application..."
            # Add your deployment commands here