name: WORKFLOW -- CI Test
on: [push]
jobs:
  ci_test_job:
    name: JOB -- CI Test Job
    runs-on: ubuntu-latest
    steps:
      - name: STEP -- Checkout repository
        uses: actions/checkout@v5

      - name: STEP -- Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24.11.0'

      - name: STEP -- Install dependencies
        run: |
            npm install -g yarn
            yarn --cwd frontend/apps/starting-app install

      - name: STEP -- Run tests
        run: |
            yarn --cwd frontend/apps/starting-app test

      - name: STEP -- Build project
        run: |
            yarn --cwd frontend/apps/starting-app build