name: Hello GitHub Actions
on: [workflow_dispatch]
jobs:
  hello_world:
    name: JOB -- Hello World 
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, GitHub Actions!"
      - name: Show current date and time
        run: date
      - name: List files in the repository
        run: ls -la
      - name: Display GitHub context
        run: echo "${{ toJson(github) }}"
      - name: multiline script
        run: |
          node -v
          npm -v